apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - reloader/install.yaml
    - kubernetes-reflector/install.yaml
    - snapshot-controller/install.yaml
    - volsync/install.yaml
    - traefik-crds/install.yaml
    - cert-manager/install.yaml
    - csi-driver-nfs/install.yaml
    - cloudnative-pg/install.yaml
    - csi-driver-smb/install.yaml
    - metallb/install.yaml
    - openebs/install.yaml
    - prometheus-operator/install.yaml
    - rook-ceph/install.yaml
    - system-upgrade-controller/install.yaml
