---
apiVersion: v1
kind: Namespace
metadata:
    name: system-upgrade
    annotations:
        volsync.backube/privileged-movers: "true"
    labels:
        kustomize.toolkit.fluxcd.io/prune: disabled
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/system-upgrade-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller-plans
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/system/system-upgrade-controller/plans
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: system-upgrade
  dependsOn:
    - name: system-upgrade-controller
  wait: false
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      TALOS_SCHEMATIC_ID_PI: 1cf3a7b9d2ebae9167a4c3b034ed890223de18bea67b4895a46df3bf5f051a82
      # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
      TALOS_VERSION: 'v1.8.0'
      # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
      KUBERNETES_VERSION: v1.30.0
