# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller-charts
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: actions-runner-large
        runnerScaleSetName: actions-runner-large
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ${ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID}
            github_app_installation_id: ENC[AES256_GCM,data:9lYI32GOVtI=,iv:S9FPzf/TInSElFc/W9bAnHt76rP6LoQPPwYo/LlBzPA=,tag:NR+3UyAYQrNhd01zZ8VDIg==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:dv2mSranzHUwSx+SNr9jc/p7O1p3WZxQ7UinDmlKCCLNjDPMointqlUAej2PzsewknTsTTDAmPLGimu4pahnzE5kqzUXRKIkF1aRjSWtwi8NwuehFhPgtj3NJW3h5K9PnkJ6h0UPXJB7hBJEHMUHYsNClzIEM3qdq03LWEhlwotW/AYgGrWzk/VGdiQRI8o+Kp5WiZzawbsMMiaAWxp0TqMozdeX8ah8SZssiBOmbfJLNY7/OVoeHTPbLA0VP1BOCnG2It6hTXvwPxU8PNerOe61jMKb2idCCIBX5CEGPsgzTF5fAW8DMBLGuQEcIhLXMHfduh7lUSfyWF4ThFEbpEUZAvLa7wxFoVT0Wg0iFl5kH9LyQBeJxnHFqE8MNxus3htxH7aC08c4CqSVwG6CtywA6Xx2Sq27XWwPcXxm3r9dwiJDWYeF+PrtmXppi+zLLlduPStR7++zL4KK5cX6I6PY0gmDnOtTIIhgpovRyZnby8KPR47dcDkbDodfy4jxSHXlsKcVTvo3SEQYZ9ngzELwZju+DYk/iHmD8ouURfh0UxGgSdelJSOwhBSM2Zw8R5TjlscehO3esDGNFe2cWZzaz8d2Ypw0qVpoIVWPcmjU05x0lAC7O38GkIY9COzW4bTTmQxB1qU70n2NBH4yuuaJ2orOLbdmvlOwd3at0Yz6y7KW2mvUihh07I+4yJHHZ3R7MvB1/l2cNMbo4AFRnZovof5PXvnQgV20j22ADv2D3Hhg1U9z2udh8eLsHhXox4YTjSqCH1rdaF2TxjduqdJaYT1XSJOoDVXESQ99i4rJLV9BYrfoXRvDT6kVqFVecO1JX0GZ10K2x9FLeNy5enVQqeQvA364LKhXwNV0DgQrqa2PRF3RFSvh1jSisLRVbaMyKoPc883WIxZbx4DjoYCOJmiWSCu8zqoRWBA6QAO/c6MGL6J9Bq2xfMCqbAJM2Y4ObALfUWucpy2gzINxC11tdb87PNT1CGkh65wuNXCIOaJQjTPZwKG+YMjDKJA0NL4z64HxUM8HQlmuJc7UBGofsOlXdcpGqLYEpMuidVgQCSakapzQ4Le51XkRJvmQnmFBsM0kk223qhk6YN3GxW0XJ+DMBpjIzMm0F1iGFrgzSfjgPf4KQLi7hr8icT16PDKyYen07owA6nqz8RWjrxjNz/RWZE+2lXu/QQM0ZRvGFJmXg5zn+mNMZHznsCagFLBBFZo3iysPBKS1BsPY45H4UnjQGdtii5B5pCbxlt5VRwMQ6k7g6bt6jofHQAEhnHKpKvzmAqydHSZbssyy35uglrAYl1vCC/MNaaztJLP+CU/av+oBC0SL7vU8D86hymi0J2ti+t5PAmC2q1fzuaXCRoEftwDHEzBgYlyVtfinixO24bl9oRiOGFSxEjre7x8/kzs4rIfPDPHujkbzVffIr7xXWXeDZX+l08d3HTVimFQ4oe3TTkCcBenUc2xb3uaW9PSyCl2ueFcHmtTaGWBIFT3cH/1PDVwRAzxPRGOcKAwGrBAms/fK6g+evvoPtj5ftvq3ggPNE+GlD/jyTCv3LhH+vU2DUq80nEjgDkqN4EJrJPloQrZk5JO+smH6x4XxdzxrUPOGPYw/iy/nDlm2YaxE3RhY5BJ3SF8sUNVtSfHtxItVSBYQfqD+G24GQHWbDfmWqHnSk+seSSXbMCNgC50EnD32niCQ5tfpzFjXVqJ0YStFjbrCb+zFeiiWWKjPk2kZJrha1ZX8JIkE328/B+0NV9Lt7G3P6rYAog9a6Y/keZc7dMkQ+w37/E7SH3m6KiWP3p+UOhMtvLBcILtwDryAdvVHsIE3NNT1qv9UfFyyRexhjehojyP1NgU0gE6sxMpcKZe2GamkqvgLRHhxqI8Eja5ydZoGhayfEQMOxU4PJbTsJPtOQ7WB10dGG5m8OD310vEq2gOprXqZ3Ib5qoy8WUH4JrFHZJAmE7ha4H7DrOy0oBSDAXrTQwXQKwluwvb0e75SLSckebv9bKVfC8iJ1tY1iRAuGuUrP7UBIJLySiPPodN+GMyO4bQpm7t1eub2gWMqGD40qOpovvj1vrDUl90vzNuW8fXKuXrpafpE3O6Zx2DDT1HJCeBY9dUM1pSyyvhCoqb4Bjy1YbzCwIMx/YY1nbsRpDQvtPWs3/XhD0/PGyOWWl4ZtpeZXsXdXr4lzohT6CEN55Q+G3HHK91acAWpLRFqEHJNNfKLJLBuQDN1jsVwxA==,iv:TfBRr9XBH9/fxYyLkEkRg0bMIwM2VaW34C9hKUp7X94=,tag:dc6PPl3Q7/vY4v9CB5iOoA==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:f140cac74f5ed15b985209dbc9b154d92df532599b7f9766cbbf4771fc0db304
                      command:
                        - /home/runner/run.sh
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Mkd5SEpZejAvcWlnNzdF
            eXhvaU0yQ3dEWXh6MW95bE8vc0VPYzA5Ymo4CkNRMU9sL1ppb3BJalZRZi9sak9R
            RVRBRHpoa2xjWFRUNGdhYnkyZXk4cUEKLS0tIGc2bEpsUWFzL0hsNEJmVytlNUs4
            R3hIT3M4c2IwZis5UDF5YWRiL2JNUzQKjXecEBIzlt5IhRkvlevEISpjorInaXDb
            VjBco/UVfUtgGFYSvnwEZb/aJxBPuOELD2UBbVGEpFzEeF64xVCs4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T19:01:53Z"
    mac: ENC[AES256_GCM,data:tgKMrcpi2SF00/cGpLJTkH7RlRY+smGPNyMtteihzIHOnh39pyT1DONfaV3retYwn/xVNtKGuhNNHXRzskNV8lmmUH3yWNJ78RNGUpt3PoeVkttk5LmyUDBBx8U6rw/CI+VLkgGI2pd1cuWKbowjzarE+uAbcLF6a7Fra24h/KM=,iv:gRnkEasYKTozrGZldpBDniygU5V0bKayhP0dugDMDYw=,tag:lyTdklV9E6RymYsmoTU/Kg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(github_app_private_key|github_app_installation_id))
    version: 3.8.1
