# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actions-runner-large
    namespace: actions-runner
spec:
    interval: 30m
    chart:
        spec:
            chart: gha-runner-scale-set
            version: 0.9.3
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: flux-system
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            strategy: rollback
            retries: 3
    dependsOn:
        - name: actions-runner-controller
          namespace: actions-runner
    values:
        nameOverride: ENC[AES256_GCM,data:PKz+KInfndbTn+5hYo/l8+9trAU=,iv:BP5U2lzCXPOha2LmcaQveJZhrr73yBCUhzbo+bEUC/8=,tag:xMsRmTBnw8hOdijKa1kt0A==,type:str]
        runnerScaleSetName: ENC[AES256_GCM,data:QB4peWIKI78bVpX8DsuDU5os3a4=,iv:lvypR7C/F/cejxO8VBTPzfZH/UBiw8YniD54rj8sVGc=,tag:/MJk7zXVKtBz7sdi7gqg3A==,type:str]
        minRunners: 3
        maxRunners: 12
        containerMode:
            type: dind
        githubConfigSecret:
            github_app_id: ENC[AES256_GCM,data:KC/9sQ4ZUzZL4Kedcm/36BozDtdSbtpbZbL/RF68WmTscDzTW+9ZlF4=,iv:aqrvE3Y7HjTDFlxtCDZfQEKv0PRClHybLmWlvFmbKOg=,tag:6iplxSdRzL905HbDNJ1reg==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:adK8Acb8WDU=,iv:jg5tEuYTLsIAQy5yXW3EKppDC3EiDLWncR2gfrzhHTc=,tag:WApAeIrxcDC1LPIkEQav+g==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:LzaxxGnVpLp6Jiy+jatoSSokamubBk65s5Spv6iFzOq2Z16VPA7JjfsWWIfvjuHlcGmRDc/4xDjcvOkI+JPom9TDGrua/PkHs7gUd9ODbSZqINJ8BWpJBb/e+h1JV4HEhKjniflMUgz8egQuRlKjKxHSCTpHaqLoT1T3qdDIqGtbOZiW4LwQCeCfFTFr8BqQcEs0ANWPm/Nfi0qoIxT94BIOWYswI9qYDfREmYcC/+6JlaZAk3o1av17O/w1fdxXa+Oyab8zZIWnRyzkjvAZO91ehd6hVFBFdeHEMza5+AqqzUShHAlh/OpY+ZudqqL5pLjrTmt/cmun9lOvg6e1pdToQXv+YyF4eS6l+nG7nTWmmmwiyQJz4hHuwkYvGzjQz9rA1Knz+AIAHOKXj4KVvr1ZxFPGYWKk12J+5xAxwUcIUIVJwjdAtHsgMk6xFt/7EMpS+0JMIAVCWJ73sNY8sL6DJpipvGAEVKi5k//skT6QWAp572CNcIE59ndwZJAAjbKq22H1+Kd/SnCIORWDixcGjt3R3A/hCXjv4wNi64y+It/bLosE3Xt9chUq4HIiOsRByWKQ1J0GI28hWs9Dt9P0k5tgISqCFj39VzdjE7eedODGJ3juGmVp2x0pK4DuDngHS0+El/c6aSBjHRvRGujrtszjenFRzJvUUwkMmkACl20Gf3h55vIu41lqArhPT2qpSkIWKun8NtOa74O4LJV/RzDf+vEDn68ghcWYQbei503RWekV23hVp2IXiuF0yrjhwXbyhqiSY5sdjri1t6pL+vjXjAdbvTxBi6w3+Dwd8nVu4mKAIrzgn0fRRcKThP37RHnzvDVUjPl79sRJAQDi76PI/3N5wk/l0UfmVbfALDMhNrEwvkAb3/Z6pW2RX61lR9MSVDNQ5bSvt23MeX103UoOlK+TxIAB+g3T5ei/I6718VzFnhcd7xhL6aktLQaLihIzQ7eLTrjuCaStUBtPAio502UvnkrQJOXt37Fx9vj7TNqokQaJNQbpbyKQyvcDY5XJhhRS4LEdXj7cpyw7+1o33ss7siSqhqHLVOd3Iz86r0B4OjxY4AfTLfgcTfm6jyzvBtGlvFexKsGDUSbB4rL/SppYSnw0xoFlVklbxK1QT81wpHxHzu5vcyM9QGFejLlPEnzwsUPv9mmsHEQS5mmZzNEhZzaNIXMputhkm+gFSTH2nIIjTt7OEa2X9tFbJaCFE6wtOyUThT+V6d8T1YYdE6ebUXoGQvFwJxgXg95iz93uU8clqZSIjcXYmebgho/7ZpyJC/WLRjxbwDkhMHerGra5cMVAnpkb83LVd1wwlQ4SoRBwvVPCCKaHUe7U79RnO2Slt4f0+eieUZaHPYIHlLut3wUCR4tTIqawhZs5G6ov4kVIIKfeVm6B/gBoEK+n2foTRf1onFcnDhLAUtAYPufhyVnCf2h1eWh+ObbXUHRi82PehJlTebY2A6ssTuOLN9hZiKpuqkA+BKSjaP0PCbw1/mf1pYyLYpIBHc6L8jLXrdjFraFyojdyoWznD6yZpus1hzMMkMNLsYw35tboXXkq070U/4igg4zrnZeEdwrjkvauf2LAGir6HC+eX0j0ghYWCERfbLyO9qnYZSWKu/m/IaL6YlTwKQK+ZmG3nI9UHu2g95g+LOymVBk/cqvD1f0vrOaHJMPzyLCK18Z9jgz/m0ctQ7zS5BEZHF5oh7fkB9MccwVrqTm/KGooIvGaZyE8MqjgGSQkbgVD7iFYMN/cZ/Beq1ausV7e8cIieGtzTCAbS8+nYdTLhm4f3XRZ8hAtCnELH2ZzI8Sy4dMbq6eswVgqbpRso+ohQcTjbqBqPbJAxPGfjAO0fH9NxSOKbgvvCIcfMfP5uuYkdRnh74/LBsuCBPoMcZ/3uKRernOXN25cWf9CpNcS7+vDItjQM+nRYa48qjWR60x3K7UPcypLdJT2jpgZdxykrrs0TVp34RByZN3OlCX+zcSaLetJZLoRbmyXjT36WH78pWZvn8bu6wjrpHC5LbRWYpQVJJ9F4rOiJah9cgGqJT6Ls2HoihVcC96V5Qg6BU6C785ffhXAJcHOzOg1niE4uQ581HpLlKaS8nbm8SLoDHR1o8LuBOP9ZE/wCg8ozPj7+WrfHNcTI252J1zZ6y6F6Mpu/RKG2oUoSYeRnn/tbZZDmR43PLoqRDPWHzLxD3psfEbNhDp+V8xAVOWn3isDSHiJ4kG7tLXH9g==,iv:2Re2lehRkm7lNhnerhpp2IaI/vTgGMt7yF/duexiIG4=,tag:XMppraM3umzJKK+Dt0gwSQ==,type:str]
        githubConfigUrl: https://github.com/truecharts
        controllerServiceAccount:
            name: actions-runner-controller
            namespace: actions-runner
        template:
            spec:
                containers:
                    - name: runner
                      image: ghcr.io/truecharts/charts-ci:latest@sha256:65e31fc0262a854e18d2f20ac8b15ec1ffce52bb602de5b7bd3aa8b3979ac1d0
                      command:
                        - /home/runner/run.sh
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRHZIMFVmQ3FxaGV3NHVp
            c1ZUUkVEVCtVMnd1K2hxVVpKNkFUZ0lyUlVBCmJabUtNOWE0VklFVmVEaFhHallp
            NmpEUHdjaVdKbHJCZWZTLzFuTWRoWnMKLS0tIG9hMDZWc0tYcWdWQitsVnc0eXhB
            WU1ZUHZVZytob21pZmFEd29HcHY1L3cK9tALCcD3h9mHv5spG4TOX2+HLYk2Hh4I
            +GFVnOZ26yhoN/B9gYwsdTxDF3RahdLtjZik7Hm5VZztl5fxgdxiWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T14:25:18Z"
    mac: ENC[AES256_GCM,data:5qWLS/Z2EUY4tFDZDmo9vCgQXvCh1feWMuiz7bTL347Rj66HGB2ljPWOVnwJE+YqOJ4AQlYlz7ec0P2D7bkgW7fP+XYm/Z2FVNR4fKMT2bb0R/BS2yIg5A8by0wXjexGAwkSZLkyaCsgZFnekyMbeqLazQpowg8V4mRfP/p+GCY=,iv:Zp9f4tMF8WQlkSDnYjpi3EoGvclNOjfxna5wKS+8kd4=,tag:O+5bCxe3gdRjZrNVWRwmtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
