clusterName: main
talosVersion: v1.5.5
kubernetesVersion: v1.28.0
endpoint: https://${VIP}:6443
allowSchedulingOnControlPlanes: false
additionalMachineCertSans:
    - ${VIP}
additionalApiServerCertSans:
    - ${VIP}
# Warning: Also used in Cilium CNI values!
clusterPodNets:
    - 172.16.0.0/16
clusterSvcNets:
    - 172.17.0.0/16
cniConfig:
  name: none
patches:
    - '@./patches/all.json'
nodes:
    - hostname: k8s-control-1
      ipAddress: ${MASTER1IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        - interface: eth0
          addresses:
            - ${MASTER1IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-2
      ipAddress: ${MASTER2IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        - interface: eth0
          addresses:
            - ${MASTER2IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-3
      ipAddress: ${MASTER3IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        - interface: eth0
          addresses:
            - ${MASTER3IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
#  - hostname: k8s-worker-1
#    ipAddress: 192.168.100.11
#    installDiskSelector:
#      size: <= 600GB
controlPlane:
    patches:
        - '@./patches/controlplane.json'
        - '@./patches/sopssecret.yaml'
        - '@./patches/kubePrism.json'
    schematic:
        customization:
            extraKernelArgs:
                - net.ifnames=0
            systemExtensions:
                officialExtensions:
                    - siderolabs/amd-ucode
                    - siderolabs/bnx2-bnx2x
                    - siderolabs/i915-ucode
                    - siderolabs/intel-ucode
                    - siderolabs/qemu-guest-agent
worker:
    patches:
        - '@./patches/worker.json'
        - '@./patches/kubePrism.json'
        # - '@./patches/nvidia.json'
    schematic:
        customization:
            systemExtensions:
                officialExtensions:
                    - siderolabs/nonfree-kmod-nvidia
                    - siderolabs/amd-ucode
                    - siderolabs/iscsi-tools
                    - siderolabs/nvidia-fabricmanager
                    - siderolabs/qemu-guest-agent
                    - siderolabs/bnx2-bnx2x
                    - siderolabs/i915-ucode
                    - siderolabs/intel-ucode
                    - siderolabs/nvidia-container-toolkit
                    - siderolabs/thunderbolt
