apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nvidia-gpu-operator
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/kube-system/nvidia-gpu-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

