apiVersion: v1
kind: ConfigMap
metadata:
  name: schematics
  namespace: system-upgrade
data:

  192.168.10.110: 1cf3a7b9d2ebae9167a4c3b034ed890223de18bea67b4895a46df3bf5f051a82
  192.168.10.120: 1cf3a7b9d2ebae9167a4c3b034ed890223de18bea67b4895a46df3bf5f051a82
  192.168.10.130: 1cf3a7b9d2ebae9167a4c3b034ed890223de18bea67b4895a46df3bf5f051a82
  192.168.10.111: dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
  192.168.10.121: dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
  192.168.10.131: dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586
  192.168.10.141: dc7b152cb3ea99b821fcb7340ce7168313ce393d663740b791c36f6e95fc8586