apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeapps
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/kubeapps/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

