apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hass/ks.yaml
  - kubernetes-dashboard/ks.yaml
  - media
  - metrics
  - mosquitto/ks.yaml
  - actions-runner/ks.yaml
  - bitmagnet/ks.yaml
  - flaresolverr/ks.yaml
  - jackett/ks.yaml
  - overseerr/ks.yaml
  - prowlarr/ks.yaml
  - tautulli/ks.yaml
  - zilean/ks.yaml
  - zurg/ks.yaml
