---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  VIP: 192.168.10.100
  MASTER1IP: 192.168.10.110
  MASTER2IP: 192.168.10.120
  MASTER3IP: 192.168.10.130
  GATEWAY: 192.168.10.1
  METALLB_RANGE: 192.168.10.230-192.168.10.250

  BASEDOMAIN: truecharts.org

  Blocky_IP: 192.168.10.230
  TRAEFIK_IP: 192.168.10.231

  EMAIL: info@truecharts.org
  CLOUDFLARE_TOKEN: <sometoken>
