apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/kube-system/intel-device-plugins/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

