apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: truecharts
    namespace: flux-system
spec:
    interval: 10m0s
    dependsOn:
    - name: kube-system
    - name: crds
    - name: operators
    - name: system
    - name: core
    - name: helm-repos
    - name: flux-config
    path: ./kubernetes/truecharts
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-age
