apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cilium/ks.yaml
  - descheduler/ks.yaml
  - intel-device-plugins/ks.yaml
  - kubelet-csr-approver/ks.yaml
  - metrics-server/ks.yaml
  - node-feature-discovery/ks.yaml
  - spegel/ks.yaml
