apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media
  - metrics
  - kms/install.yaml
  - homepage/install.yaml
  - hass/install.yaml
  - mosquitto/install.yaml
  - kubeapps/install.yaml
  - actions-runner/install.yaml
