---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operators-openebs
  namespace: flux-system
spec:
  path: ./kubernetes/operators/openebs/app
  dependsOn:
    - name: operators-prometheus-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
