apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: autobrr
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/media/autobrr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

