apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - authentik/ks.yaml
  - blocky/ks.yaml
  - clusterissuer/ks.yaml
  - crowdsec/ks.yaml
  - metallb-config/ks.yaml
  - rook-ceph/ks.yaml
  - traefik/ks.yaml
  - kyverno-policies/ks.yaml
  - system-upgrade-controller-plans/ks.yaml
  - actions-runner-controller/ks.yaml
