---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - downloads-nfs-pvc.yaml
  - media-nfs-pvc.yaml
  - media-backups-pvc.yaml
  - jackett/install.yaml
  - lidarr/install.yaml
  - prowlarr/install.yaml
  - qbittorrent/install.yaml
  - radarr/install.yaml
  - sonarr/install.yaml
  - bazarr/install.yaml
  - overseerr/install.yaml
  - tautulli/install.yaml
