apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/kyverno/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster