apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crowdsec
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/crowdsec/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

