apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: speedtest-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/metrics/speedtest-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

